"""empty message

Revision ID: 04789bafe8ab
Revises: 
Create Date: 2025-11-04 13:41:55.629215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04789bafe8ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date', sa.Float(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_title'))
        batch_op.drop_index(batch_op.f('ix_event_location'))
        batch_op.drop_index(batch_op.f('ix_event_description'))
        batch_op.drop_index(batch_op.f('ix_event_date'))

    op.drop_table('event')
    # ### end Alembic commands ###
